version: '3.3'
services:
  capgo: 
    image: capgo
    ports:
      - 3333:3333
    environment:
      - HOST=0.0.0.0
      - PORT=3333
    env_file:
      - .env
    # networks:
    #   - traefik-public
# volumes:
#   capgo-data:

# networks:
#   traefik-public:
#     external: true